# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    cascade_invocations: false
    comment_references: false
    constant_identifier_names: true
    one_member_abstracts: false
    prefer_relative_imports: true
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    non_constant_identifier_names: false

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/localization/*.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/riverpod_graph.dart'
    - '**/util/assets/*.gen.dart'
  errors:
    invalid_annotation_target: ignore