name: counter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  riverpod: ^2.3.7
  simple_logger: ^1.9.0+2
  stacked_card_carousel: ^0.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true

import_path_converter:
  relative: true

import_sorter:
  comments: false
