name: counter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  blur: ^3.1.0
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  flutter_riverpod: ^2.3.7
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.5.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^10.1.1
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  modal_bottom_sheet: ^3.0.0-pre
  sign_in_with_apple: ^5.0.0
  simple_logger: ^1.9.0+2
  stack_trace: ^1.11.0
  stacked_card_carousel: ^0.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/

import_path_converter:
  relative: true

import_sorter:
  comments: false
